### ISSUE TITLE
Exit Lobby after Game creation

### ISSUE THREAD

**Issue by iankhou** [chinese-board-games/luzhanqi-web#48]
# Description

As a user, I want to be able to leave a game after I've created it, but before it has started.

AC:
- Player is able to leave Lobby by clicking/pressing a button
- If player is last person in Lobby, Game is deleted (in DB) when player leaves
- If the player is not the host, the player becomes the host if the only one left in the Lobby

## Type of Issue

- [X] New feature
- [ ] Bug fix
- [ ] Documentation update

**Comment by javacoder720** [comment]
Abort game feature?
